apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: volsync-restic-{{ name | slugify }}-secrets
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: volsync
    app.kubernetes.io/instance: volsync
    app.kubernetes.io/managed-by: volsync-operator
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: volsync
    app.kubernetes.io/created-by: volsync-operator
data:
  RESTIC_PASSWORD: {{ restic_password | b64enc }}
  RESTIC_REPOSITORY: {{ restic_repository | b64enc }}
  AWS_ACCESS_KEY_ID: {{ aws_access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY:  {{ aws_secret_access_key | b64enc }}
