apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-operator-role-cluster
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims, persistentvolumeclaims/status]
    verbs: [get, list, watch, patch] # Patch is required so that the DiffBase storage can create the necessary annotations
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: ["volsync.backube"]
    resources: [replicationsources]
    verbs: [get, list, watch, create, update, patch]
