---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - deployment.yaml

namespace: volsync-system

commonLabels:
  app.kubernetes.io/component: volsync-operator
  app.kubernetes.io/instance: volsync
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: volsync-operator
  app.kubernetes.io/part-of: volsync

images:
  - name: volsync-operator
    newName: juniorfoo/volsync-operator
    newTag: latest
