apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: volsync-operator
build:
  artifacts:
    - image: volsync-operator
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - manifests/operator

